/// Domain tree types — the typed parse tree.
///
/// These mirror askicc's aski/*.aski definitions.
/// In the bootstrap they're hand-written Rust.
/// In the self-hosted engine they'll be generated by askicc.
///
/// rkyv derives enable .sema serialization.



// ── Classification types (from aski-core via cc) ────────────

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum NameDomain {
    Type, Variant, Field, Trait, Method,
    Module, Literal, TypeParam,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum Operator {
    Add, Sub, Mul, Mod,
    Eq, NotEq, Lt, Gt, LtEq, GtEq,
    And, Or,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum ScopeKind {
    Root, Module,
    Enum, Struct, Newtype, Trait, TraitImpl,
    Method, Block, MatchArm, Loop, Iteration,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Visibility { Exported, Local }

#[derive(Debug, Clone, PartialEq)]
pub struct Span { pub start: u32, pub end: u32 }

// ── Name wrapper (scoped identity) ──────────────────────────

#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub struct Name(pub String);

impl Name {
    pub fn new(s: &str) -> Self { Name(s.to_string()) }
}

// ── Type expressions (from askicc/aski/type.aski) ───────────

#[derive(Debug, Clone)]
pub enum TypeExpr {
    Simple(Name),
    Application { constructor: Name, args: Vec<TypeExpr> },
    Param(Name),
    BoundedParam { bounds: Vec<Name> },
    InstanceRef { constructor: Name, args: Vec<TypeExpr> },
}

// ── Root-level definitions (from askicc/aski/root.aski) ─────

#[derive(Debug, Clone)]
pub enum RootChild {
    Module(ModuleDef),
    Enum(EnumDef),
    Struct(StructDef),
    Newtype(NewtypeDef),
    TraitDecl(TraitDeclDef),
    TraitImpl(TraitImplDef),
    Const(ConstDef),
    Ffi(FfiDef),
    Process(Block),
}

#[derive(Debug, Clone)]
pub struct ModuleDef {
    pub name: Name,
    pub exports: Vec<Name>,
    pub imports: Vec<ModuleImport>,
    pub span: Span,
}

#[derive(Debug, Clone)]
pub struct ModuleImport {
    pub source: Name,
    pub names: Vec<Name>,
}

#[derive(Debug, Clone)]
pub struct EnumDef {
    pub name: Name,
    pub children: Vec<EnumChild>,
    pub span: Span,
}

#[derive(Debug, Clone)]
pub enum EnumChild {
    Variant { name: Name, span: Span },
    DataVariant { name: Name, payload: TypeExpr, span: Span },
    StructVariant { name: Name, fields: Vec<StructField>, span: Span },
    NestedEnum(EnumDef),
    NestedStruct(StructDef),
}

#[derive(Debug, Clone)]
pub struct StructDef {
    pub name: Name,
    pub children: Vec<StructChild>,
    pub span: Span,
}

#[derive(Debug, Clone)]
pub enum StructChild {
    TypedField { name: Name, typ: TypeExpr, span: Span },
    SelfTypedField { name: Name, span: Span },
    NestedEnum(EnumDef),
    NestedStruct(StructDef),
}

#[derive(Debug, Clone)]
pub struct StructField {
    pub name: Name,
    pub typ: TypeExpr,
    pub span: Span,
}

#[derive(Debug, Clone)]
pub struct NewtypeDef {
    pub name: Name,
    pub wraps: TypeExpr,
    pub span: Span,
}

#[derive(Debug, Clone)]
pub struct ConstDef {
    pub name: Name,
    pub typ: TypeExpr,
    pub value: LiteralValue,
    pub span: Span,
}

#[derive(Debug, Clone)]
pub enum LiteralValue {
    Int(i64),
    Float(f64),
    Str(String),
}

#[derive(Debug, Clone)]
pub struct FfiDef {
    pub library: Name,
    pub functions: Vec<FfiFunction>,
    pub span: Span,
}

#[derive(Debug, Clone)]
pub struct FfiFunction {
    pub name: Name,
    pub params: Vec<Param>,
    pub return_type: Option<TypeExpr>,
    pub span: Span,
}

// ── Expressions (from askicc/aski/expr.aski) ────────────────

#[derive(Debug, Clone)]
pub enum Expr {
    BinAdd { left: Box<Expr>, right: Box<Expr>, span: Span },
    BinSub { left: Box<Expr>, right: Box<Expr>, span: Span },
    BinMul { left: Box<Expr>, right: Box<Expr>, span: Span },
    BinMod { left: Box<Expr>, right: Box<Expr>, span: Span },
    BinEq { left: Box<Expr>, right: Box<Expr>, span: Span },
    BinNotEq { left: Box<Expr>, right: Box<Expr>, span: Span },
    BinLt { left: Box<Expr>, right: Box<Expr>, span: Span },
    BinGt { left: Box<Expr>, right: Box<Expr>, span: Span },
    BinLtEq { left: Box<Expr>, right: Box<Expr>, span: Span },
    BinGtEq { left: Box<Expr>, right: Box<Expr>, span: Span },
    BinAnd { left: Box<Expr>, right: Box<Expr>, span: Span },
    BinOr { left: Box<Expr>, right: Box<Expr>, span: Span },
    FieldAccess { object: Box<Expr>, field: Name, span: Span },
    MethodCall { object: Box<Expr>, method: Name, args: Vec<Expr>, span: Span },
    TryUnwrap { inner: Box<Expr>, span: Span },
    InstanceRef { name: Name, span: Span },
    PathVariant { typ: Name, variant: Name, span: Span },
    PathMethod { typ: Name, method: Name, args: Vec<Expr>, span: Span },
    IntLit { value: i64, span: Span },
    FloatLit { value: f64, span: Span },
    StringLit { value: String, span: Span },
    InlineEval(Block),
    Match(MatchExpr),
    Loop(Loop),
    Iteration(Iteration),
    StructConstruct { typ: Name, fields: Vec<FieldInit>, span: Span },
}

#[derive(Debug, Clone)]
pub struct FieldInit {
    pub name: Name,
    pub value: Box<Expr>,
}

// ── Statements (from askicc/aski/statement.aski) ────────────

#[derive(Debug, Clone)]
pub enum Statement {
    EarlyReturn(Box<Expr>),
    Loop(Loop),
    Iteration(Iteration),
    LocalTypeDecl { name: Name, typ: TypeExpr, span: Span },
    Mutation(Mutation),
    Instance(Instance),
    Expr(Box<Expr>),
}

#[derive(Debug, Clone)]
pub struct Instance {
    pub name: Name,
    pub type_annotation: Option<TypeExpr>,
    pub value: Box<Expr>,
    pub span: Span,
}

#[derive(Debug, Clone)]
pub struct Mutation {
    pub name: Name,
    pub method: Name,
    pub args: Vec<Expr>,
    pub span: Span,
}

#[derive(Debug, Clone)]
pub struct Loop {
    pub condition: Option<Box<Expr>>,
    pub body: Vec<Statement>,
}

#[derive(Debug, Clone)]
pub struct Iteration {
    pub source: Box<Expr>,
    pub body: Block,
}

// ── Bodies (from askicc/aski/body.aski) ─────────────────────

#[derive(Debug, Clone)]
pub struct Block {
    pub statements: Vec<Statement>,
    pub tail: Option<Box<Expr>>,
}

#[derive(Debug, Clone)]
pub enum MethodBody {
    Block(Block),
    Match(MatchExpr),
    Loop(Loop),
    Iteration(Iteration),
    StructConstruct { typ: Name, fields: Vec<FieldInit>, span: Span },
}

#[derive(Debug, Clone)]
pub enum Param {
    BorrowSelf,
    MutBorrowSelf,
    OwnedSelf,
    Named { name: Name, typ: TypeExpr },
    Bare { name: Name },
}

// ── Match (from askicc/aski/pattern.aski) ───────────────────

#[derive(Debug, Clone)]
pub struct MatchExpr {
    pub target: Option<Box<Expr>>,
    pub arms: Vec<MatchArm>,
}

#[derive(Debug, Clone)]
pub struct MatchArm {
    pub patterns: Vec<Pattern>,
    pub result: Box<Expr>,
}

#[derive(Debug, Clone)]
pub enum Pattern {
    Variant(Name),
    VariantBind { variant: Name, binding: Name },
    OrPattern(Vec<Name>),
    StringLit(String),
}

// ── Traits (from askicc/aski/trait.aski) ────────────────────

#[derive(Debug, Clone)]
pub struct TraitDeclDef {
    pub name: Name,
    pub signatures: Vec<MethodSig>,
    pub span: Span,
}

#[derive(Debug, Clone)]
pub struct MethodSig {
    pub name: Name,
    pub params: Vec<Param>,
    pub return_type: Option<TypeExpr>,
    pub span: Span,
}

#[derive(Debug, Clone)]
pub struct TraitImplDef {
    pub trait_name: Name,
    pub type_name: Name,
    pub methods: Vec<MethodDef>,
    pub span: Span,
}

#[derive(Debug, Clone)]
pub struct MethodDef {
    pub name: Name,
    pub params: Vec<Param>,
    pub return_type: Option<TypeExpr>,
    pub body: MethodBody,
    pub span: Span,
}

// ── The top-level output ────────────────────────────────────

#[derive(Debug, Clone)]
pub struct AskiProgram {
    pub children: Vec<RootChild>,
}
